XGovFormBuilder/digital-form-builder

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- Oops. I think I need this table for GitHub to pick them up in the issue picker.
I can't.. until it reaches master :)
=> fix issue templates

designer/client/component-create.js, designer/client/component-edit.js, designer/client/component-type-edit.js, designer/client/helpers.js, designer/client/index.js, designer/client/link-create.js, designer/client/link-edit.js, designer/client/model/data-model.js, designer/client/notify-edit.js, designer/client/page-create.js, designer/client/page-edit.js, designer/client/page.js, designer/index.js, designer/package-lock.json, designer/package.json, designer/test/data-model.test.js, designer/test/email-edit.test.js
Introduce a basic data model to promote code reuse and help encapsulate knowledge of the data structure - making it easier to change.
* Implement allInputs and findPage functions
* Use them in place of corresponding logic
* Fix some linting errors and make linting part of the build
* introduce the ability to redefine clone on an object so that
function implementations and type information still exist
=> Introduce a basic data model

runner/readme.md
-readme changed to include configuration required for setting up a windows machine to build and run runner
=> updated runner readme to include windows setup

.gitignore, engine/components/constants.js, engine/components/datepartsfield.js, engine/components/datetimepartsfield.js, engine/components/factory.js, engine/components/index.js
Fixes issue #32 - Optional text being displayed on sub components
=> Optional text fixes

designer/.babelrc, designer/client/conditions/inline-condition-operators.js, designer/client/conditions/inline-conditions-definition.js, designer/client/conditions/inline-conditions.js, designer/client/model/data-model.js, designer/package-lock.json, designer/package.json, designer/test/data-model.test.js, designer/test/inline-condition-operators.test.js, designer/test/inline-conditions-definition.test.js, designer/test/inline-conditions-edit.test.js, designer/test/inline-conditions.test.js
Include sub components of list items in condition builder. Also support checks on the length of text, multiline text and email inputs
=> Conditions

.dockerignore, engine/package-lock.json, engine/package.json, runner/package-lock.json, runner/package.json
Closes #43 
Remove type: module from engine and add missing dependency on babel runtime.
=> #43 Resolve import issue

.circleci/config.yml
=> STP-577. Switching off the forced build.

designer/server/index.js
Adjust Desginer's server port.
=> Adjust designer server port

designer/server/index.js
=> adjust port

runner/README.md, runner/src/server/config.ts, runner/src/server/index.js, runner/src/server/plugins/builder/pages/summary.js
Refactor environment variables names and add documentation.
=> Refactor notify variables and add documentation

designer/server/views/help/accessibility-statement.html, designer/server/views/help/cookies.html, designer/server/views/layout.html
Adjust Designer Header and Footer width:
- Remove wrappers around header and footer.
- Add placehold text. 
the testing if necessary. 
- [N/A] I have made corresponding changes to the documentation and versioning
=> Stp 897 adjust designer footer header width

.github/workflows/deploy-development.yml
=> Tag latest image

.github/workflows/deploy-development.yml, designer/Dockerfile, runner/Dockerfile
Fix incorrect application image build.
- Deprecate yarn focus in production
- Build model/runner/designer
- Adjust image tag
- [N/A] I have made corresponding changes to the documentation and versioning
- [N/A] I have added tests that prove my fix is effective or that my feature works
=> Adjust docker files and dev deployment image tag

designer/server/views/help/accessibility-statement.html
Style changes to accessibility-statement.html
=> STP-626 Style changes

designer/Dockerfile, runner/Dockerfile
Adjust appuser app files access to 777.
=> Adjust appuser permission to 777

README.md
=> fix readme CONTRIBUTING.md url

designer/webpack.config.js
=> Fix script loading order

designer/client/index.tsx
Fix designer App component setFunctions binding bug.
=> Adjust setFunctions binding

designer/server/plugins/designer.ts
Refactor introduced an unexpected change in the /{id}/api/data response format which caused the designer client to fail to parse form's JSON configuration.
=> Fix bug with designer server endpoint

.github/workflows/publish-images.yml
- Removing -test to just leave $buildno-rc for the tags 
N/A
N/A
=> remove -test- from tag string

.github/workflows/publish-images.yml
=> add back :latest tag

designer/Dockerfile, runner/Dockerfile
- Deprecate Dockerfile `COPY .git` command from designer and runner
=> Deprecate Copy Git

runner/Dockerfile
- Fix Runner Dockerfile ARG typo
=> Fix Runner Dockerfile ARG typo

designer/client/__tests__/ComponentTypeEdit.jest.tsx, designer/client/i18n/translations/en.translation.json
This is a minor text adjustment requested by Haymond as FORM-215 ticket was outdated.
- Adjust hint text and tests.
=> Adjust Selection field optional checkbox hint text

designer/server/plugins/routes/api.ts
- route.options.payload.parse = true
- stringify output as well jic
=> more logging, parse payload

designer/client/pages/LandingPage/LandingPage.scss, designer/client/styles/index.scss, runner/src/client/sass/modal-dialog.scss
Removing duplicate and overridden styles in Sass classes. 
running designer and runner locally. Verified that duplicate/overridden style is no longer present in styles. Visually no impact to designer or runner. 
Smoke tests executed locally. 
- [X ] My changes do not introduce any new linting errors
=> removed duplicate and overridden style from classes

.github/workflows/master--lint-unit-build-and-publish-images.yml
- Adjust master workflow tag-branch setting
=> Adjust master workflow tag-branch setting

designer/server/__tests__/view.jest.ts, designer/server/createServer.ts
Adding 'X-XSS-Protection' Header HTTP Security Header , 'X-Content-Type-Options' Header HTTP Security Header
=> FORMS-358: Add missing headers

.github/workflows/branch--lint-unit-and-smoke-test.yml, .github/workflows/master--lint-unit-build-and-publish-images.yml, designer/server/config.ts
- Generate .env file with LAST_COMMIT and LAST_TAG inside workflow step and add to workspaces
- Adjust designer `.env` path
=> Create .env in branch

.github/workflows/branch--lint-unit-and-smoke-test.yml, .github/workflows/master--lint-unit-build-and-publish-images.yml
- Adjust echo `.env` file path
=> Adjust .env echo file path

designer/server/views/help/terms-and-conditions.html, runner/src/server/views/help/terms-and-conditions.html
Added noreferrer to anchors which open a new tab to satisfy sonarqube security alert. 
- [X ] Bug fix (non-breaking change which fixes an issue)
run locally, visually verified. 
Smoke tests run
Unit tests run on designer and runner
- [X ] My changes do not introduce any new linting errors
=> added noreferrer to <a> which open in new tab

.github/workflows/smoke-tests-heroku.yml, smoke-tests/designer/wdio.heroku.conf.js
Adding notification hook for nightly job failures
=> Add slack hook to nightly smoke

runner/src/server/forms/test.json
replacing test form so it sends an email
=> fix test form

smoke-tests/designer/data/componentFieldData.js, smoke-tests/designer/features/pageComponents.feature, smoke-tests/designer/features/pageobjects/pages/preview.page.js, smoke-tests/designer/features/steps/steps.js, smoke-tests/designer/wdio.debug.conf.js, yarn.lock
Created an automated test, it checks that you can progress from a page that has a checkbox component to the next logically linked page. 
The test was created using the red-green-refactor cycle and currently does not pass due the issue we discovered, it has been tagged as @wip and will not run until the fix has been introduced and the @wip tag is removed.
=> Created a scenario for testing Checkboxes in the preview

designer/server/createServer.ts, runner/src/server/index.ts
-  hsts security header configuration modified in runner
- security configuration modified in designer to look like runner
=> feature - hsts header

designer/.gitignore, designer/jest.client.config.js, designer/jest.config.js, designer/jest.server.config.js, designer/package.json, model/jest.config.js, runner/package.json
FORMS-448 -Adding code coverage thresholds
Build will fail if code coverage thresholds are not met
=> FORMS-448 -Adding code coverage thresholds

designer/README.md, designer/package.json, model/README.md, runner/README.md, yarn.lock
updating readme for test coverage threshold
- [X ] New feature (non-breaking change which adds functionality)
=> updating readme for test coverage threshold

README.md
updating documentation around which yarn should be installed
=> update readme - yarn instructions

.github/workflows/branch--lint-unit-and-smoke-test.yml, .github/workflows/codeql-analysis.yml, .github/workflows/main--lint-unit-build-and-publish-images.yml
- This pull request is to test the pipelines, it makes no real change to the software.
=> this change is just to test the full pipeline functions as expected

.github/workflows/branch--lint-unit-and-smoke-test.yml, .github/workflows/main--lint-unit-build-and-publish-images.yml
=> Test for main

.github/workflows/deploy-development.yml, .github/workflows/main--lint-unit-build-and-publish-images.yml, .github/workflows/notify-external-repositories.yml, GitVersion.yml, README.md
#546 
- For main QA runs, using GitVersion https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/index.md to calculate new tags
- GitVersion config
- start versions from 3 
- will need a supplementary PR to remove that line from GitVersion.yml
new tag format will be
3.0.4-rc.24
{major}.{minor}.{patch}-{PreReleaseLabel}.{PreReleaseNumber}
- [n/a] I have checked deployments are working in all environments
- [n/a] I have …
=> Chore/run numbers #546

runner/src/server/plugins/engine/components/FlashCard.ts, runner/test/cases/server/plugins/engine/Flashcard.test.ts
- Fixed flashcards so they render the lists properly
```js
{
"name": "uYSmR3HwHo",
"title": "How to get your vehicle importation letter and take your statutory declaration",
"type": "string",
"items": [
{
"text": …
```
=> fix: flashcard

runner/src/server/plugins/engine/components/TelephoneNumberField.ts, runner/test/cases/server/plugins/engine/TelephoneNumberField.test.ts
closes: #585 
via JSON only (there is an existing bug across all component edits in the designer)
- Allow min and max characters for telephone field
- Allow custom regex 
- [na] I have checked deployments are working …
=> minor: allow regex, min and max configuration

.github/workflows/branch--lint-unit-and-smoke-test.yml, .github/workflows/main--lint-unit-build-and-publish-images.yml
- Modified docker layer cache key to renew daily
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [n/a] I have updated the architecture diagrams as per Contribute.md
=> Changed docker layer caching to daily

runner/src/server/plugins/engine/models/submission/NotifyModel.ts
I was getting an issue with hoek.flatten, the personalisations were actually coming up empty..! 
- Tidy up using a reducer 
- using hoek.reach which is a safer way of accessing the variables 
- [na] I have checked …
=> patch: fix missing email field 

runner/src/server/plugins/applicationStatus.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/views/pay-error.html, runner/test/cases/server/upload.test.js
- clean up applicationStatus webhook logic
- add a paymentSkipped flag if a user failed a payment 
- fix pay-error template so it redirects/posts to the correct place 
- make file upload messages  error nicer (copy from design system)
applicable. To flag the change to QA assign **@XGovFormBuilder/qa** as one …
=> fix: redirecting when payment failed 

model/src/data-model/types.ts, runner/src/server/plugins/engine/models/SummaryViewModel.ts, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
- Remove `this.setFeedbackDetails` call so that SummaryViewModel can handle it itself 
- [na] I have checked deployments are working in all environments
=> fix: add feedbackLink to summaryViewModel correctly

.github/workflows/main--lint-unit-build-and-publish-images.yml, GitVersion.yml
3rd time lucky..
- change GitVersion config
- change CI to add +3 to the calculated version
- for whatever reason, GitVersion wont take the latest tag as the base version ¯\_(ツ)_/¯ 
- …
=> fix: auto-increment

.github/workflows/main--lint-unit-build-and-publish-images.yml, .github/workflows/smoke-tests-heroku.yml
- fixing so tags/releases happen in the right order 
=> move +3 to major before publishing

runner/src/server/config.ts, runner/src/server/plugins/logging.ts, runner/src/server/services/uploadService.ts, runner/test/cases/server/config.test.js
=> fix: log level

runner/src/server/plugins/engine/components/EmailAddressField.ts, runner/src/server/plugins/engine/components/TelephoneNumberField.ts, runner/test/cases/server/plugins/engine/EmailAddressField.test.ts, runner/test/cases/server/plugins/engine/TelephoneNumberField.test.ts
closes: #534 
- for prebuilt components like telephone or email address autocomplete option wasn't being passed onto the component to render. I have barcoded these since autocomplete for these fields should be either tel or email anyway
- also removed this since schema is a joi object by that time (not what is found in the JSON), so max.length was some random joi javascript being rendered in the front end. 
```.js
{
maxlength: schema.max,
};
```
Please describe the tests that you ran to verify your changes. …
=> chore: autocomplete-#534

runner/src/server/plugins/applicationStatus.ts, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
=> fix: use config.payReturnUrl #646

runner/src/server/plugins/engine/models/submission/FeesModel.ts
=> Fix use of multiplier to calculate total fee.

designer/client/components/CustomValidationMessage/CustomValidationMessage.tsx, designer/client/i18n/translations/en.translation.json, designer/client/reducers/component/componentReducer.options.ts, model/src/components/types.ts, runner/src/server/plugins/engine/components/DatePartsField.ts, runner/src/server/plugins/engine/components/FormComponent.ts, runner/src/server/plugins/engine/components/ListFormComponent.ts, runner/src/server/plugins/engine/components/TelephoneNumberField.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/pageControllers/validationOptions.ts, runner/test/cases/server/plugins/engine/TelephoneNumberField.test.ts
fixes: #620 
- change how error messages are provided, in the joi documentation it is not recommended to iterate through `any.error` for overriding messages https://joi.dev/api/?v=17.4.2#anyerrorerr
- using joi message templates
applicable. To flag the change to QA assign **@XGovFormBuilder/qa** as one of …
=> fix error messages and rename `customValidation` to `customValidationMessage`

runner/src/server/plugins/views.ts
Capitilize serviceName view value
=> minor: Capitalize serviceName

designer/client/component.js, designer/client/components/ComponentCreate/__tests__/ComponentCreateList.test.tsx, designer/client/components/ComponentCreate/__tests__/__snapshots__/ComponentCreateList.jest.tsx.snap, designer/client/i18n/translations/en.translation.json, model/src/components/component-types.ts, model/src/components/types.ts, runner/src/server/plugins/engine/components/MonthYearField.ts, runner/src/server/plugins/engine/components/NumberField.ts, runner/src/server/plugins/engine/components/index.ts, runner/src/server/plugins/engine/pageControllers/validationOptions.ts, runner/src/server/plugins/engine/views/components/monthyearfield.html, runner/test/cases/server/plugins/engine/MonthYearField.test.ts
-  Add a month year component
- behaves similarly to the address component (which is just an aggregate of other components) 
- some minor tidying 
<details>
<summary>using this .json</summary>
<code>
{
"metadata": …
=> minor: add month/year year component

runner/src/server/services/payService.ts, runner/test/cases/server/services/payService.test.ts
As well tested as the previous PR was, I got the amount wrong (pounds not pence) so displaying incorrectly.
=> fix: currency formatting

runner/src/server/services/webhookService.ts
Adding some logging, just in case the error msg is empty..
=> chore: add webhook request body

runner/src/server/plugins/engine/models/SummaryViewModel.ts, runner/src/server/plugins/engine/models/submission/WebhookModel.ts
- Adding fees back into webhook data
=> fix: add fees to webhook data

runner/src/server/plugins/engine/models/SummaryViewModel.ts
=> add fees object to SVM

runner/src/client/sass/_hmpo.scss
=> fix: flashcard styling

runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts
fixes: #565
- remove !!repeatField from params
=> fix: #565-optional-fields-override

runner/src/server/plugins/engine/components/DatePartsField.ts, runner/test/cases/server/plugins/engine/datepartsfield.test.ts
fixes #685
- return the first error message from the errors list
<details>
<summary>Screenshot</summary>
</details>
=> fix: #685 Date validation message

model/src/components/types.ts, model/src/schema/schema.ts, runner/src/server/plugins/engine/components/DateField.ts, runner/src/server/plugins/engine/components/DatePartsField.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/pageControllers/validationOptions.ts, runner/test/cases/server/plugins/engine/datefield.test.ts, runner/test/cases/server/plugins/engine/datepartsfield.test.ts, runner/test/cases/server/plugins/engine/numberField.test.ts, runner/test/cases/server/plugins/engine/pageControllers/PageControllerBase.test.ts
From DFE 
> There appears to be a problem with the error messages not appearing for new component validation -  This has occurred in the latest code which did not exist in the code base before the most recent change and was fine on 25th Nov.2021  - this is reproducable when either date ranges are used on a new Date component or a number range in a new Number component , so when running the Preview and keying values out of range no error occurs
☝️ from what I can see, the date component (not date parts) didn't handle maxDaysInFuture|Past at all. I've added that in now with some tests 
- Fix: #584 for number fields
- schema was throwing an error a form/component was PUT to the server
- Add min/max to number fields (wasn't there before..!) 
- Amend Date field to allow …
=> fix: number validation

model/src/data-model/types.ts, model/src/schema/schema.ts, runner/src/server/plugins/engine/models/submission/NotifyModel.ts, runner/src/server/services/notifyService.ts, runner/src/server/services/statusService.ts, runner/test/cases/server/plugins/engine/NotifyModel.test.ts, runner/test/cases/server/plugins/engine/NotifyViewModel.json
- allow replyToIds to be used https://docs.notifications.service.gov.uk/node.html#send-an-email-method
=> feature: add ability to configure replytos

runner/src/client/sass/_global-styles.scss, runner/src/client/sass/application.scss
The file _hmpo.scss won't compile to css
=> chore: #716 Turn on global styles for the runner

model/src/components/types.ts, runner/src/server/plugins/engine/components/MultilineTextField.ts, runner/src/server/plugins/engine/components/WebsiteField.ts, runner/src/server/plugins/engine/components/types.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/pageControllers/validationOptions.ts, runner/src/server/plugins/engine/views/components/multilinetextfield.html, runner/test/cases/server/plugins/engine/MultilineTextField.test.ts, runner/test/cases/server/plugins/engine/TelephoneNumberField.test.ts
- remove coupling from helper function and use more explicit joi configuration
- add character and word count support 
- add tests for MultilineTextField
=> minor: refactor MultilineTextField

designer/server/views/help/cookies.html
- Added a caption for the cookies table for [issue 390](https://github.com/XGovFormBuilder/digital-form-builder/issues/390)
=> #390 Adding caption

.github/workflows/branch--lint-unit-and-smoke-test.yml, .gitignore, lighthouserc.js, runner/src/server/forms/components.json
- Lighthouse for runner and designer
- Changes to components.json to match current schema layouts (removing list out of options)
=> #126 lighthouse on ci

runner/config/custom-environment-variables.json, runner/config/default.js, runner/src/server/plugins/logging.ts, runner/src/server/utils/configSchema.ts
- add logPrettyPrint 
- add redactPaths
=> feature: more logging controls

runner/config/default.js, runner/package.json, runner/src/server/utils/configSchema.ts
- remove from start script
- update config schema
=> fix: remove NODE_ENV=development from start script.

designer/package.json, model/package.json, runner/src/server/plugins/engine/components/DateTimeField.ts, runner/src/server/plugins/engine/components/DateTimePartsField.ts, runner/src/server/plugins/engine/models/FormModel.ts, yarn.lock
- Removed remaining uses of moment
=> #115 Fix/remove moment

runner/src/server/plugins/applicationStatus.ts, runner/src/server/services/payService.ts
- webhookData just needs to be updated
I've also created another ticket for this #787 which is I think the root of the problem (things are happening/created where they shouldn't be so it's hard to keep track of stuff!)
applicable. To flag the change to QA assign **@XGovFormBuilder/qa** as one of the …
=> fix: update webhookData when fee is retried

designer/client/list/ListEdit.tsx, smoke-tests/designer/wdio.conf.js
- Fix Error message on list creation
- [Link to the related issue and recreation steps](https://github.com/XGovFormBuilder/digital-form-builder/issues/719)
- To Reproduce
Steps to reproduce the behavior:
1. Go to the …
=> 719 Fix: Clear list error when adding a list item to a list

designer/client/outputs/outputs-edit.tsx, smoke-tests/designer/wdio.conf.js
- Outputs should now display on the outputs page
- [Link to the issues for bug recreation steps](https://github.com/XGovFormBuilder/digital-form-builder/issues/812)
=> Fix: Outputs not displaying

runner/src/server/plugins/engine/components/TextField.ts, runner/test/cases/server/plugins/engine/components/TextField.test.ts
- Fixing issue with regex not being applied via component.schema
=> fix: textfield regex

.github/dependabot.yml, .github/workflows/dependency-review.yml
some changes to dependabot, including reassigning PRs to me instead of greg 🤞
=> dependabot

.github/pull_request_template.md, .github/workflows/smoke-test.yml, .github/workflows/smoke-tests-heroku.yml, docker-compose.smoke.yml, e2e/cypress/e2e/runner/initialiseSession.feature, e2e/cypress/e2e/runner/initialiseSession.js, e2e/cypress/fixtures/initialiseSession.json, e2e/cypress/support/step_definitions/runner/the_form_string_exists.js, runner/src/server/plugins/initialiseSession/initialiseSession.ts, runner/src/server/plugins/initialiseSession/types.ts, runner/src/server/views/summary.html
=> feat: initialise with htmlMessage

runner/config/custom-environment-variables.json, runner/config/default.js, runner/src/server/services/cacheService.ts
- Added `confirmationSessionTimeout`, defaulting to 20 * minute.
=> feat: confirmation session timeout

e2e/cypress/support/step_definitions/common/i_see_the_error_string_for_string.js, runner/src/server/plugins/engine/models/FormModel.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts
- fix dateForComparison. was using `add` - but did not pass in a date. 
=> fix: dateForComparison

designer/webpack.config.js, e2e/cypress/e2e/runner/backLinkFallback.feature, e2e/cypress/e2e/runner/backLinkFallback.js, e2e/cypress/fixtures/backLinkFallback.json, model/src/schema/schema.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts
- Allows `backLinkFallback` to be configured for non-special pages
```.json
"pages": [
{
"backLinkFallback": "/help/cookies",
"title": "start page",
"path": "/start",
"components": [],
"next": [
{
"path": "/second-page"
}
]
},
]
```
`backLinkFallback` is only used if there is no existing session data for this form. 
=> feat: add backlink fallback

runner/Dockerfile
There were a couple of packages that were raised as security vulnerabilities on a recent pen test. These have now been solved by updating packages in the runner docker image
- Added line at the beginning of the dockerfile to update npm to the latest version of 9.x.x
- Added line to upgrade linux packages to update libcrypto package to latest version
=> patch: update-node-alpine-vulnerabilities

runner/src/server/services/statusService.ts
- Correctly store paymentSkipped after the status is checked
=> fix: store paymentSkipped correctly

designer/package.json, docs/runner/templating.md, package.json, runner/src/server/services/statusService.ts, yarn.lock
In some situations it might be necessary to change the next steps text that is shown to the user based on values from earlier in the form. This has now been implemented.
=> feat: allow templating in confirmation page next steps

README.md, designer/Dockerfile, package.json, runner/Dockerfile, runner/package.json, submitter/Dockerfile
Node 16 has reached EOL, although node 20 is the LTS version it may be too much work currently to upgrade straight to node 20. So, we're updating to node 18 in the first instance, with the expectation of moving to node 20 later on this year.
=> chore: Updated images to node 18

runner/src/server/services/statusService.ts
Payment skipped text would not accept templating variables before. Sometimes this is required to give the user relevant information
=> feat: Add templating to payment skipped message

runner/src/server/plugins/engine/components/CheckboxesField.ts
Previously checkbox fields were still required when the field was set to be optional. This PR fixes that.
=> fix: checkbox optional validation

designer/package.json, package.json, runner/package.json, runner/src/server/views/layout.html, yarn.lock
Updating to v4.8.0 for the new Tudor crown
https://github.com/alphagov/govuk-frontend/releases/tag/v4.8.0
=> feature: update to use Tudor crown

runner/src/server/services/pgBossQueueService.ts
This change is to prevent extraneous polling of the DB for submissions that have completed or failed. 
Even though the job has status failed, it was still received by the process and is "safe". Support engineers will need to remediate the issue, however, the user will still be shown the application complete screen. 
- Return reference and status in `getReturnRef`, to signal to `pollForRef` whether or not to keep retrying
=> fix: prevent extraneous polling after complete or failed received

designer/Dockerfile, runner/Dockerfile, submitter/Dockerfile
- Upgrading all images to node 20
=> feature: upgrading to node 20

model/src/components/types.ts, runner/src/server/plugins/engine/components/FileUploadField.ts
- Accept attribute can now be configured for file upload fields
=> feat: allow accept attribute to be configurable for file upload fields

designer/package.json, model/package.json, package.json, runner/package.json, yarn.lock
- Updating to the latest v4.x.x version of govuk-frontend
=> patch: update govuk-frontend for new coat of arms

.github/workflows/deploy-development.yml
=> fix: use npx heroku

runner/src/server/plugins/engine/components/NumberField.ts
- Min and max validation values were not being applied to NumberField when user filled out an optional NumberField, editing the joi validation logic to fix  
=> Fix NumberField optional validation 

runner/config/production.json
Fix the Production variable name for Production to ensure CSRF protections are enabled.
- Rename 'enableCSRF' to its correct variable name 'enforceCSRF'
=> fix: Update Csrf protection variable name in production.json

README.md
- New support information in readme
=> chore: update readme with new support information

.github/workflows/branch--lint-unit-and-smoke-test.yml, .github/workflows/dependency-review.yml, .github/workflows/smoke-test.yml, docker-compose.smoke.yml, runner/src/server/plugins/engine/components/TelephoneNumberField.ts
- We were seeing an issue where customValidationMessages for TelephoneNumberField were not passed through when the field was optional and always getting the default message, this fixes that issue 
=> fix: telephone number field optional validation

runner/src/server/views/partials/summary-card.html, runner/src/server/views/repeating-section-summary.html
Cosmetic changes to recently-added view files.
=> Update repeating-section-summary.html and summary-card.html

docs/runner/mini-summary-page-controller.md, e2e/cypress/e2e/runner/MiniSummaryPageController.feature, e2e/cypress/fixtures/mini-summary-fields.json, runner/src/server/plugins/engine/pageControllers/MiniSummaryPageController.ts, runner/src/server/plugins/engine/pageControllers/helpers.ts, runner/src/server/plugins/engine/pageControllers/index.ts, runner/src/server/plugins/engine/views/partials/form.html, runner/src/server/views/mini-summary.html
MiniSummaryPageController is a new page controller that can be used within any form.
This allows you to see a summary of a section of form data, or the first section if a section isn't specified.
- Page controller and associated view form added
- A change to an HTML partial means that the button will say 'Confirm and continue' on pages utilising this controller
What is the type of change you are making?
PR titles should be prefixed with the type of change you are making, based on the [README.md#versioning](https://github.com/XGovFormBuilder/digital-form-builder?tab=readme-ov-file#versioning).
This is so that when performing a squash merge, the PR title is automatically used as the commit message.
Have you updated the PR title to match the type of change you are making?
Have you added …
=> feature: add MiniSummaryPageController
