XGovFormBuilder/digital-form-builder

designer/client/component-create.js, designer/test/component-create.test.js
Alphabetical ordering of component types in create component
Also added tests for display of component create. Unfortunately
submit requires too much rework to support testing currently.
Unit tests of component-create.js
Click testing of create component
=> Alphabetical ordering of component types

designer/client/conditions-edit.js, designer/client/conditions/inline-conditions.js, designer/client/conditions/select-conditions.js, designer/test/select-conditions.test.js
Display placeholder message when users cannot define a condition
=> Display placeholder message when users cannot define a condition

designer/client/helpers.js, designer/client/page-create.js, designer/client/page-edit.js, designer/test/page-create.test.js
Fixing the automatic generate of page paths
- Trim string before replacing spaces with hyphens
- Replace all whitespace chars / multiple successive whitespace chars with a single '-'
- Extract common utility method to ensure consistency
=> Fixing page path issues

designer/client/conditions/select-conditions.js, designer/client/link-edit.js, designer/client/model/data-model.js, designer/test/data-model.test.js, designer/test/link-edit.test.js, designer/test/select-conditions.test.js
Description
Make link-edit consistent with the inline condition builder approach.
Wire condition builder into link-edit
SelectConditions component now supports a default selected condition
Data class now supports updating a link
Type of change
Bug fix (non-breaking change which fixes an issue)
How Has This Been Tested?
Unit tests
Click testing
Checklist:
My code follows the javascript standard style
I have performed a self-review of my own code
I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation and versioning
My changes generate no new warnings
I have added tests that …
=> Wire condition builder into link-edit

designer/client/component-type-edit.js, designer/client/helpers.js, designer/test/component-type-edit.test.js, designer/test/helpers/element-assertions.js, designer/test/inline-conditions-edit.test.js, engine/components/index.js
- Allow users to hide title on inputs
- Optional checkbox pre-populated on component edit
- Optional checkbox no longer has a hint relating to the 'hint' input
=> Hide title for inputs

runner/src/server/services/webhookService.ts, runner/test/cases/server/services/webhookService.test.ts
Runner's webhook service should handle response payload as string. 
This PR extends Webhook service so it can handle payloads both as string and JSON. 
the testing if necessary. 
- [N/A] I have made corresponding changes to the documentation and versioning
=> Handle webhook response payload as string and test

designer/server/lib/persistence/previewPersistenceService.ts, designer/server/plugins/designer.ts
Edit existing configuration in preview mode
- Revert `uploadConfiguration` implementation in preview's persistence service
- Skip `uploadConfiguration` when in preview mode
=> Re-implement uploadConfiguration and ignore it when in preview mode

README.md
This change fixes a typo as some formatting in the readme:
- fix `desginer` -> `designer`
- fix indentation of code blocks
- pull the explainer text out of the code block
- switch to `json5` syntax to stop comments appearing as errors
Documentation change
N/A
I don't think most of this applies, but please let me know if I'm wrong.
=> Fix a typo and some formatting in the readme

.github/workflows/smoke-tests.yml
- Configure github smoke-tests workflow to cach yarn cache.
=> Configure smoke-tests workflow to cache yarn dependencies

designer/Dockerfile, runner/Dockerfile
- Adjust designer and runner Dockerfile to build using user 1001 to avoid EACCES bug on ACP.
=> build with non-root user and chown when copying

designer/client/components/FieldEditors/para-edit.tsx, designer/client/reducers/component/componentReducer.fields.ts, designer/client/reducers/component/componentReducer.options.ts, designer/client/reducers/component/types.ts, model/src/components/types.ts
bug report:
> If I create a condition from Edit Conditions > add an inset text component > set the condition to the one I just created and save > go back into the component, the conditions field is blank (the condition doesn't apply to Preview either)
- change options.conditions to options.condition
- add types
Acceptance criteria 
Given I have a page with an inset text component and conditions available to select
When I select a condition and click save
Then after re-opening the page, I can see my selected condition
applicable. To flag …
=> Bug/forms 209-conditions persist

designer/client/components/ComponentCreate/ComponentCreate.tsx, designer/client/components/ComponentCreate/__tests__/ComponentCreate.jest.tsx
This is a simple work around the bug with `CreateComponent Flyout` scrolling in small screens so we can solve the bug with the least amount of effort. 
- Implement a fast two phase render to allow DOM to reflow Flyout without the list, thus resesting it's scroll position
- Adjust tests
As a user
Given I have a small screen
When I click `Create component`
And scroll down the components list 
And select `YesNo Field`
Then the `Component Edit` screen renders without being scrolled to the bottom
=> Forms 223 flyout scrolling issue

model/src/data-model/__tests__/data-model.test.ts, model/src/data-model/data-model.ts
fixes #219
bug fix  -  cycle in page links is causing the link condition drop down preparation logic to throw stack overflow exception
- method in Data model changed to not process already visited nodes 
- [] I have made corresponding changes to the documentation and versioning
=> bug fix for FORMS-136 and issue 219

.eslintrc.json, designer/client/__tests__/ComponentTypeEdit.jest.tsx, designer/client/components/ComponentCreate/ComponentCreate.tsx, designer/client/components/ComponentListSelect/component-list-select.tsx, designer/client/field-edit.tsx, designer/client/i18n/translations/en.translation.json, designer/client/styles/index.scss, designer/jest-setup.js, model/src/components/component-types.ts
- Implement text changes to List based fields components. 
- Fix test warning because `ComponentCreate` effect was invoked when component was already unmounted. 
- Adjust Jest's document body to represent actual page body (needed to render portals)
- Eslint ignore `*.scss` files
=> Forms 215 selection fields text changes

.github/workflows/master--lint-unit-build-and-publish-images.yml, designer/server/config.ts, runner/src/server/config.ts
- Create a `.env` file inside workspaces with required environment variables
- Adjust process.env variables defaults (not sure why Joi ignored previous `.default()`
=> Set workspace .env inside action and default to undefined

.github/workflows/branch--lint-unit-and-smoke-test.yml, .github/workflows/master--lint-unit-build-and-publish-images.yml, designer/server/__tests__/config.jest.ts, designer/server/config.ts, runner/src/server/config.ts, runner/test/cases/server/config.test.js
Problem: With last changes in CI we are now building images with `docker-compose`. During the build compose sets both `LAST_TAG` and `LAST_COMMIT` ARG values and these are then turned into ENVIRONMENT variables in Dockerfile ([see here](https://github.com/XGovFormBuilder/digital-form-builder/blob/master/designer/Dockerfile#L49)). 
The problem is that when the resulting images are executed outside the compose environment Docker will again try to configure both variables and because the expected arguments are not provided those variables endup being set as empty strings.
To solve this the CI is building a `.env` file with these variables and adding it to both runner and designer workspaces, and because we need to allow ACP to overwrite LAST_COMMIT and LAST_TAG, these variables are being …
=> Allow last TAG and COMMIT from GH and ACP environment

smoke-tests/designer/support/hooks.js
Enable scenario and steps run times to the report to allow further analysis on long running features/scenarios/steps
The smoke-tests were run and the report was checked to see if the new data was present.
=> Display Scenario run times on the report

designer/server/plugins/routes/healthCheck.ts, runner/src/server/routes/health-check.ts
Adding uptime to the health check endpoint, so we can see how long the service has been up for.
=> Adding uptime to health check

runner/src/server/services/httpService.ts, runner/test/cases/server/services/httpService.test.ts
Payments were failing to be processed because Gov Pay request payload was being stringified, probably a bug introduced during refactor
=> Fix httpService response payload format

runner/src/server/plugins/applicationStatus.ts, runner/src/server/plugins/engine/helpers.ts, runner/src/server/plugins/engine/index.ts, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts, runner/test/cases/server/plugins/engine/helpers.test.ts
Urls used for payments (which are set via environment variables) were failing because they were incorrectly treated as relative urls. This PR improves the fixes I added yersterday, adding a specific helper method which follows the already existing way of building redirect urls which copies over the existing query parameters.
=> Fix non-relative payment related urls

designer/client/i18n/translations/en.translation.json, designer/client/pages/ErrorPages/SaveError.tsx, designer/client/pages/ErrorPages/__tests__/SaveError.jest.tsx, runner/src/server/plugins/applicationStatus.ts
Error message on save error page changed , the save error page was originally intended for errors while saving components , but since we cannot differentiate save of other form details vs save of components , error message is made generic 
- Change i18n text
- Change test case
=> Error hint made more generic

runner/src/server/plugins/engine/components/AutocompleteField.ts, runner/test/cases/server/plugins/engine/components/AutocompleteField.test.ts
Fix bug where Autocomplete input was showing the first autocomplete option by default.
- Overriding Autocomplete getViewModel to include the first empty item and test
=> Fix/runner autocomplete missing empty option 

runner/src/server/plugins/engine/components/ListFormComponent.ts, runner/test/cases/server/plugins/engine/components/ListFormComponents.test.ts, smoke-tests/designer/features/steps/completeAForm.steps.js
Bug: If we create a list with numeric values and assign it to any list based component, the selected value(s) appear in the summary page as `not supplied`
**Steps to Reproduce**:
1. Load the following form: 
{"startPage":"/first-page","pages":[{"title":"First page","path":"/first-page","components":[{"values":{"type":"listRef","list":"UTITt1"},"name":"GI4G9Q","options":{},"type":"RadiosField","title":"Turnaround time?"}],"next":[{"path":"/summary"}]},{"title":"Summary","path":"/summary","controller":"./pages/summary.js","components":[]}],"lists":[{"title":"Turnaround","name":"UTITt1","type":"string","items":[{"text":"1 hour","value":"1"},{"text":"2 hours","value":"2"}]}],"sections":[],"phaseBanner":{},"metadata":{},"fees":[],"outputs":[],"version":2,"conditions":[]}
2. Preview it on …
=> fix: Make sure types are correct before strictly comparing and tests

designer/client/__tests__/helpers.jest.tsx, designer/client/helpers.js
When changing a list, with a list item with either the `name` or `value` is `1`, isEmpty(1) will return true and prevent saving from occurring. 1 is truthy in js, so doing !1 (without checking if it was a string/number) was causing issues
- If nothing is supplied to the function, default str to ""
- wrapped the parameter incase the value was a number
Before PR's can be merged they will …
=> fix: isEmpty function and add tests

designer/package.json, package.json, runner/package.json, runner/public/static/govuk-template.js, runner/src/client/sass/_hmpo.scss, runner/src/client/sass/application.scss, runner/src/server/index.ts, runner/src/server/plugins/views.ts, runner/src/server/routes/public.ts, runner/src/server/views/layout.html, runner/src/server/views/partials/cookie-banner.html, runner/test/cases/server/plugins/router.test.ts, yarn.lock
- Upgrade runner's govuk-frontend dependency.
- Refactor cookie banner to use latest govuk-frontend `govukCookieBanner` macro.
- Refactor `addCookieMessage` helper to implement latest `cookies_policy` pattern which is used in `gov.uk`.
=> Cookie banner

designer/client/reducers/component/componentReducer.options.ts
Fixed bug where multiple options couldn't be checked at once on a component in the designer
- Changed [Line 18 of componentReducer.options.ts](https://github.com/XGovFormBuilder/digital-form-builder/blob/main/designer/client/reducers/component/componentReducer.options.ts#L18) from:
`{ options } = state`
to:
`{ options } = selectedComponent`
=> fix: changed options reducer in designer to get options from selectedComponent

runner/src/server/services/payService.ts, runner/test/cases/server/services/payService.test.ts, smoke-tests/designer/wdio.conf.js
Current use of numbers leads to '£3.5' rather than '£3.50' in description. Updating to use Intl.
Added unit tests ... 😱 
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation and versioning
- [x New and existing unit tests pass locally with my changes
=> Switch to using Intl.NumberFormat to format Pay descriptions.

runner/package.json, runner/src/server/plugins/engine/components/ComponentBase.ts, runner/src/server/plugins/engine/components/DatePartsField.ts, runner/src/server/plugins/engine/components/FormComponent.ts, runner/src/server/plugins/engine/components/MonthYearField.ts, runner/src/server/plugins/engine/components/types.ts, runner/src/server/plugins/engine/models/SummaryViewModel.ts, runner/src/server/plugins/engine/models/submission/WebhookModel.ts, runner/src/server/plugins/engine/models/submission/index.ts, runner/src/server/plugins/engine/models/types.ts, runner/test/cases/server/plugins/engine/SummaryViewModel.json, runner/test/cases/server/plugins/engine/WebhookModel.test.ts, yarn.lock
- refactor SummaryViewModel.parseDataForWebhook as it's own function
- tidy up some of the iterations 
- fix date format for webhooks 
- change `get dataType()` into a field (getter wasn't getting invoked properly; was returning undefined) 
- added `answerFromDetailItem()` which makes it easier to change/return the desired value for a webhook
- typings
- add date-fns (moment is self deprecated), keeping both until we can refactor moment out..
Please describe the tests that you ran to verify your changes. Provide …
=> fix: return yyyy-MM-DD for webhooks 

runner/src/server/plugins/engine/components/DateField.ts, runner/src/server/plugins/engine/components/FileUploadField.ts, runner/src/server/plugins/engine/models/submission/WebhookModel.ts, runner/src/server/plugins/logging.ts, runner/src/server/services/webhookService.ts, runner/test/cases/server/services/webhookService.test.ts
- replace `get dataType()` with a property. The getter didn't seem to be returning anything so was defaulting to text
- force prettyPrint off for non localhost 
=> fix: replace dataType getter with property 

runner/src/server/plugins/engine/components/helpers.ts, runner/test/cases/server/plugins/engine/components/TextField.test.ts, smoke-tests/designer/wdio.conf.js
Fixes #690
- Allow null and "" input in text field if set to optional
- Explicitly set `.optional()` on the schema in the above case - I don't think this is strictly needed since we're allowing null and empty input, but is seemingly required to make the `presence` check in the test give the correct result
- Basic functional test - submitted form without address line 2 and checked that it passed 
- Some manual regression testing - checked that:
- Other text fields are still required
- Fields set to optional in the CMS are optional
- Data for these fields is still collected (appears on the summary page) 
- [na (very minor change) ] I have commented my code, particularly in hard-to-understand areas
- [na] I have checked deployments are working in …
=> fix: make address line 2 optional

runner/README.md, runner/src/server/config.ts, runner/src/server/plugins/engine/models/SummaryViewModel.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts, runner/src/server/plugins/views.ts, runner/src/server/views/layout.html, runner/test/cases/server/feedback.json, runner/test/cases/server/forms/phase-alpha.json, runner/test/cases/server/forms/phase-default.json, runner/test/cases/server/forms/phase-none.json, runner/test/cases/server/phase-banner.test.js
Fixes #706 
Phase banner now reflects option set in form config. If no option set in form config, the phase tag shows as set in ENV config. Finally, the phase tag defaults to 'BETA' for backwards compatibility (linked layout template bug means 'BETA' is always shown).
Unit tests added to test rendering of phase banner.
To manually test:
1. Create new form in designer
2. Check preview: phase banner should show 'BETA'
3. Edit form details and choose 'Alpha' for phase banner
4. Check preview: phase banner should show 'ALPHA'
5. Edit for and choose 'None' for phase banner
6. Check preview: phase banner should not be shown
applicable. To flag the change to QA assign …
=> fix: phase banner tag

designer/client/components/Menu/Menu.tsx, designer/client/components/Menu/__tests__/Menu.jest.tsx, designer/client/declaration-edit.js
Fixes #699 
Includes:
- Fixes onCreate calls in Menu component
- Remove onCreate prop from menu items which don't use it
- Slight edit to DeclarationEdit component so the save logic matches the other menu components
- [ n/a ] I have checked deployments are working in all environments
- [ n/a ] I have updated the architecture diagrams as per Contribute.md
=> Fix: close menu flyouts on save

designer/client/components/Visualisation/Lines.tsx, designer/client/components/Visualisation/__tests__/Visualisation.jest.tsx
Fixes #701 
Fixes #702 
- Link polylines in the visualisation now have `role="button"` and an appropriate `title` so that screen reader users know they can be used to edit the corresponding link
- Space bar and enter events on the link polyline will open the Edit Link menu - thi smatches the behaviour of native buttons
- [ n/a ] I have made corresponding changes to the documentation and versioning
- [ n/a ] I have checked deployments are working in all environments
- [ n/a ] I have updated the architecture diagrams as per Contribute.md
=> fix: visualisation link a11y fixes

designer/server/createServer.ts, runner/src/server/index.ts
Update: server options to handle trailing slash
Update: runner to use port from environment if provided
It simply enabled route option to strip trailing slash and, adds OR condition in  reading PORT number in runner, which is already set exactly the same way in designer
Prior to these changes, health-check of docker container deployed in cloud foundry were  failing to start only because of health-check failure 
- [ x] Bug fix (non-breaking change which fixes an issue)
We have build and deployed docker container with this code on PaaS platform, and it is no more crashing because of health-check failure
- [ x] My changes do not introduce any new linting errors
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x …
=> minor: Enable health-check to pass on PaaS platform (cloud foundry)

designer/client/component.js, designer/client/components/Page/Page.tsx, smoke-tests/designer/wdio.conf.js
- Removed the drag marker and made the whole component draggable. Decrease the press time to improve hit box click delay.
-*Issue*  Still slightly hit or miss. What i have noticed is that if your cursor is still moving, even only slightly, the drag wont register. I think this may be an issue with [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) and not our app
[link to issue and recreation steps](https://github.com/XGovFormBuilder/digital-form-builder/issues/784)
Please describe the tests …
=> #784 Improve Component order dragging

designer/client/ComponentEdit.js
Currently page components that are deleted from a page is done in post-order and not in-order. This change changes deletion to in-order [#758](https://github.com/XGovFormBuilder/digital-form-builder/issues/758)
Ran jest
=> fix: components do not delete inorder

docs/adr/0002-save-and-return.md, model/src/components/types.ts, runner/config/production.json, runner/src/client/sass/application.scss, runner/src/server/plugins/engine/components/AutocompleteField.ts, runner/src/server/plugins/engine/components/ListFormComponent.ts, runner/src/server/plugins/engine/components/SelectField.ts, runner/src/server/plugins/engine/components/TextField.ts, runner/src/server/plugins/engine/models/FormModel.ts, runner/src/server/plugins/engine/models/SummaryViewModel.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/pageControllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts, runner/src/server/plugins/engine/pageControllers/helpers.ts, runner/src/server/plugins/engine/plugin.ts, runner/src/server/plugins/initialiseSession/initialiseSession.ts, runner/src/server/services/cacheService.ts, runner/src/server/services/uploadService.ts, runner/src/server/types.ts, runner/src/server/views/repeating-summary.html, runner/test/cases/server/plugins/engine/components/TextField.test.ts, smoke-tests/designer/wdio.conf.js
- Add RepeatingFieldPageController and RepeatingSummaryPageController
- `RepeatingFieldPageController` 
- modifies the stateSchema to allow multiple answers (i.e. array) for one page. 
- GET (makeGetRouteHandler) 
- `?view=summary` - renders the summary page. 
- `?view=number` - renders the question page at index `number`. 
- if the question is list based, remove the items from the list 
- POST (makePostRouteHandler+ 
- redirects to ?view=summary if successful. otherwise rerenders the page with errors (TODO: implement Post Redirect Get pattern globally, …
=> feat: repeating page

runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
The purpose of this PR is super specific. If there is a summary page with a declaration at the bottom of it, there are cases where the `request.headers. referer ` does not exist (like if the user has an ad blocker). In those cases if a user ignore the tickbox and submits the form, they get an error.
This fix addresses that so that the user is redirected to the page with an error message.
=> fix: add condition for if header.referrer can't be found

runner/config/default.js, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts, runner/src/server/services/cacheService.ts
- If a pay property is detected in the state object, set the TTL to 90 minutes
- gov.uk pay session is 90 minutes. It is possible that a user takes longer to pay than 20 minutes, but by that time their session would have died. 
- Add logging of webhook data before redirecting to pay or /status
=> fix: add paymentSessionTimeout

designer/client/conditions/InlineConditions.tsx, designer/client/conditions/SelectConditions.tsx, designer/client/conditions/__tests__/conditionsByType.jest.ts, designer/client/conditions/select-condition-helpers.ts
Conditions which relied on fields that sat within sections weren't showing in the list of conditions to add to links. This meant that if a condition was defined inline that the value of the condition on. the link was an empty class, since the dropdown list still had no values after the condition was created.
- Related to #1018, update SelectConditions component to strip the section prefix from the field name on the condition, so that these conditions were still being registered
- Added delete button to conditions for ease of use, as during testing noticed it was quite annoying that I could add loads of conditions but couldn't delete them
=> #1018 issues with conditions in sections

designer/client/data/types.ts, designer/client/list/ListEdit.tsx, designer/client/list/ListItemEdit.tsx, designer/client/outputs/__tests__/output-edit.jest.tsx, designer/client/outputs/notify-edit-items.tsx, designer/client/outputs/notify-edit.tsx, designer/client/outputs/outputs-edit.tsx, e2e/cypress/e2e/designer/notifyOutput.feature, e2e/cypress/e2e/designer/notifyOutput.js, e2e/cypress/fixtures/notifyOutput.json, e2e/cypress/support/step_definitions/designer/i_am_viewing_the_designer.js, model/src/components/types.ts, runner/src/server/plugins/engine/models/submission/NotifyModel.ts, runner/src/server/plugins/engine/models/submission/__tests__/NotifyModel.test.json, runner/src/server/plugins/engine/models/submission/__tests__/NotifyModel.test.ts
During work on a form we realised that in some scenarios there may be large conditional lists that need to be shown to the user. Currently, this logic can be recreated in the GOVnotify template by passing through all of the conditions and duplicating the list's conditional logic in the template. However, for larger lists, this could become quite cumbersome.
As a solution to this, conditional lists could be passed into the GOVnotify template by transforming the list into a notify-formatted string.
- Added a `parseListAsNotifyTemplate` function and `checkItemIsValid` function to the notify model to allow the processing of lists
- updated designer type data file so that list components and flash card component are filtered out of the govnotify variable list
- updated components data model to …
=> Added the ability to pass through conditional lists to a GOVnotify template

runner/src/server/plugins/engine/models/submission/NotifyModel.ts, runner/src/server/plugins/engine/models/submission/__tests__/NotifyModel.test.json, runner/src/server/plugins/engine/models/submission/__tests__/NotifyModel.test.ts
Fix of #1079 . The list that is parsed in the notifyModel is now appended to an empty string so that if no list items are shown, an empty string is passed to the personalisation.
=> fix: lists passed to GOVnotify work with no list items shown

e2e/cypress/e2e/runner/initialiseSession.feature, e2e/cypress/e2e/runner/initialiseSession.js, runner/Dockerfile, runner/config/default.js, runner/config/test.json, runner/src/server/plugins/applicationStatus.ts, runner/src/server/plugins/applicationStatus/checkUserCompletedSummary.ts, runner/src/server/plugins/applicationStatus/handleUserWithConfirmationViewModel.ts, runner/src/server/plugins/applicationStatus/index.ts, runner/src/server/plugins/applicationStatus/retryPay.ts, runner/src/server/plugins/initialiseSession/types.ts, runner/src/server/plugins/logging.ts, runner/src/server/services/statusService.ts
For session initialisation `POST /session/:formId`, allow the application complete page to be skipped and redirect to a different page entirely.
The request options are now:
```.ts
export type InitialiseSessionOptions = {
callbackUrl: string;
redirectPath?: string;
message?: string; // summary page message
htmlMessage?: string; // summary page message
title?: string; // summary page title
skipSummary?: { // new 
redirectUrl: string; // URL to redirect to 
};
customText: { // confirmation page 
title: string;
paymentSkipped?: false | string;
nextSteps?: false | string;
};
components: ContentComponentsDef[];
}
```
⚠️ The user's answers will be cleared immediately after a successful submission. If a user attempts to return to `/:formid/status` they will be redirected to the configured link …
=> redirect after submission

runner/src/server/views/help/cookies.html
There was no statement for GTM cookies being shown when GTM is enabled on the form runner. Information on Matomo was also hardcoded to show. This has been changed so both are conditional now.
=> Feat: Added conditional cookie statements for GTM and Matomo to form runner

runner/src/server/plugins/engine/plugin.ts
Currently, if no default form is set and a user navigates to the root of the service, they are presented with a 404. This change will make it so that when a user navigates to the root of a service, and the service has a start page set, the user will instead be redirected to the specified start page
=> feat: add homepage redirect

runner/src/server/services/uploadService.ts
Updated upload service to expect errors relating to image quality from OCR image checking.
- Updated UploadService.parseDocumentUploadResponse to use an error message from the document upload api if one was returned
- Otherwise, standard response handling is done
=> feat: add-ocr-support

docs/runner/fee-options.md, model/src/data-model/types.ts, model/src/schema/__tests__/schema.test.ts, model/src/schema/schema.ts, runner/src/server/plugins/applicationStatus/index.ts, runner/src/server/plugins/applicationStatus/retryPay.ts, runner/src/server/plugins/engine/models/FormModel.feeOptions.ts, runner/src/server/plugins/engine/models/FormModel.ts, runner/src/server/plugins/engine/models/SummaryViewModel.ts, runner/src/server/services/statusService.ts, runner/src/server/views/pay-error.html, runner/test/cases/server/services/statusService.test.ts
As a failsafe, if a user was not able to pay, we will allow them to try up to 3 times, then auto submit.
This feature now allows this behaviour to be configurable. 
You must migrate any top level fee related options into the new feeOptions key. These are `paymentReferenceFormat` and `payApiKey`. 
in the form json,
```.json5
{ //..
feeOptions: {
"payApiKey": {
"test": "test_key_123",
"production": "production_key"
},
// optional
// "paymentReferenceFormat": "",
// optional, if you want to override PAY_RETURN_URL global env var
// "payReturnUrl": joi.string().optional(),
// defaults to true to replicate existing behaviour
// set to false if you do not want to allow users to submit without paying
"allowSubmissionWithoutPayment": false,
// defaults to 3. this has no affect if …
```
=> add more feeOptions

runner/config/default.js, runner/config/development.json, runner/src/server/prismaClient.ts, runner/src/server/utils/configSchema.ts
- Prevents prisma from attempting to connect if ENABLE_QUEUE_SERVICE is true
- exits runner with exit code 1 if QUEUE_DATABASE_URL is not configured
- ensure queue service is not turned on by default
=> fix: prevent prisma from initialising preemtively

docs/runner/fee-options.md, model/src/data-model/types.ts, model/src/schema/__tests__/schema.test.ts, model/src/schema/schema.ts, runner/src/client/sass/application.scss, runner/src/server/plugins/applicationStatus/index.ts, runner/src/server/plugins/applicationStatus/paymentSkippedWarning.ts, runner/src/server/plugins/engine/models/FormModel.feeOptions.ts, runner/src/server/plugins/engine/models/FormModel.ts, runner/src/server/plugins/engine/models/SummaryViewModel.ts, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts, runner/src/server/services/payService.ts, runner/src/server/views/payment-skip-warning.html, runner/src/server/views/summary.html
Allow the user to skip payment from the summary page, but allow a warning page to be configured.
https://github.com/XGovFormBuilder/digital-form-builder/assets/22080510/747158e1-b0e2-4bff-b7f5-5e1248676629
- add a new feeOption (bool) `showPaymentSkippedWarningPage`. `allowSubmissionWithoutPayment` must also be true.
- add a new specialPage, `specialPages.paymentSkippedWarningPage`
- add a GET route `/{id}/status/payment-skip-warning`
- this will render `runner/src/server/views/payment-skip-warning.html`
- content is configurable via paymentSkippedWarningPage
=> feat: add pay warning page

runner/src/server/forms/runner-components-test.json, runner/src/server/plugins/engine/components/ListFormComponent.ts, runner/test/cases/server/plugins/engine/SummaryViewModel.json, runner/test/cases/server/plugins/engine/components/ListFormComponents.test.ts
ListSelectionFields (Radios, select) do not allow no/empty answer when set to `{ required: false }`
- set schema correctly
- add tests
=> fix: allow selection fields to be optional

runner/src/server/plugins/engine/plugin.ts, runner/src/server/plugins/router.ts, runner/src/server/views/help/cookies.html
At some point there was an update to the way cookies were saved, but the content on the cookies page hadn't been updated to reflect this.
In addition to this there was previously no way to reset cookies after setting them initially, unless the user manually cleared their cookies. This update adds a form to the cookies page allowing the user to update their preferences at any time.
=> fix: Update cookies page to describe cookies accurately and to allow changes to consent from cookies page

runner/config/default.js, runner/src/server/utils/configSchema.ts, runner/test/cases/server/config.test.js
Previously when running smoke tests, if you needed to check confirmation page content based on the user having paid for their application, you would need to use a version of the service accessible by https. This change will allow redirect to http applications (including localhost) when either the current node environment or api environment are in test mode or development mode.
=> fix: Updated pay return url to allow insecure redirect urls if the environment is in test

designer/client/i18n/translations/en.translation.json, designer/client/section/section-edit.js, model/src/data-model/types.ts, model/src/schema/schema.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/test/cases/server/titles.json, runner/test/cases/server/titles.test.js
In some instances it might be necessary to keep sections for the sake of making the summary page easier to read, but the flow of the sections may be confusing to the user. In these cases it may be necessary for the user's journey to keep the pages and sections in this order, and therefore may be a better user experience if section titles are hidden.
This PR adds an optional flag to sections `hideTitle` which will hide the section title for all pages that use that section title.
=> feat: hide section titles

runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/plugin.ts
Previously, due to the form progress being empty in the state, the user would be automatically redirected to the start page even if they were using query parameters to skip these pages. This PR adds a `hasPrepopulatedSessionFromQueryParameter` flag to the request pre object to prevent redirecting in this first instance.
=> fix: prevent form runner from automatically redirecting to start page when query params have been filled in

docs/runner/submission-queue.md, runner/config/custom-environment-variables.json, runner/config/default.js, runner/src/server/services/pgBossQueueService.ts, runner/src/server/utils/configSchema.ts
For slow webhooks, you may now increase how long to wait for a reference number. 
- allow `QUEUE_SERVICE_POLLING_TIMEOUT` to be configurable by env var.
=> feat: allow pollingTimeout to be configured for pgboss

docs/runner/submission-queue.md, model/src/schema/schema.ts, runner/config/custom-environment-variables.json, runner/config/default.js, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/plugin.ts, runner/src/server/services/pgBossQueueService.ts, runner/src/server/utils/configSchema.ts
Merging the beta branch into main. The changes include:
- Allow the next page to be a redirect to another URL. It must be a fully qualified URL.
```
{
"pages": [
{
"title": "Start",
"path": "/start",
"section": "beforeYouStart",
"components": [
{
"name": "country",
"type": "AutocompleteField",
"title": "Country",
"nameHasError": false,
"list": "SfkWjb"
}
],
"next": [
{
"path": "/second-page"
},
{
"redirect": "http://localhost:3009/help/cookies",
"condition": "shouldRedirectToCookiesPage"
"path": "/second-page"
}
]
},
]
}
```
- https://github.com/XGovFormBuilder/digital-form-builder/pull/1191
- https://github.com/XGovFormBuilder/digital-form-builder/pull/1192
=> feat: allow redirects to be configured in next; query param redirect; add polling timeout

docs/runner/redirects.md, e2e/cypress/e2e/runner/redirect.feature, e2e/cypress/fixtures/redirects.json, model/src/schema/schema.ts
- Add docs and smoke tests to #1197. [docs can be found at docs/runner/redirects.md](https://github.com/XGovFormBuilder/digital-form-builder/blob/265ef52fd3cc5758f56cce2a0f9ce014a6c17e2e/docs/runner/redirects.md)
=> feat: allow next links to be configured with a redirect

docs/runner/fee-options.md, model/src/data-model/types.ts, model/src/schema/schema.ts, runner/src/server/plugins/engine/models/SummaryViewModel.ts, runner/src/server/services/queueStatusService.ts, runner/src/server/services/statusService.ts, runner/src/server/services/webhookService.ts
Some apis may not be compatible with the new pay metadata schema introduced by the fee options object. To overcome this we've added a toggle to allow webhooks to choose whether to send this data through.
=> feat: added toggle for new metadata being sent to webhook

runner/src/server/views/upload-playback.html
Previously the messaging for how to take a good photograph included laying the document "against a wall". This could be confusing and frustrating for users, so this line has been removed.
=> fix: update "how to take a good photograph" advice on image playback

runner/src/server/services/queueStatusService.ts
For forms using the queue service, but calling webhooks that can't handle the additional pay metadata, additional pay metadata was still being passed through, even when explicitly excluded in the webhook output configuration.
This has now been fixed so that the additional pay metadata has been removed in the same way it's removed from the standard webhook service
=> fix: conditionally remove additional pay metadata from queue service webhook

model/src/components/types.ts, runner/src/server/plugins/engine/components/AutocompleteField.ts, runner/src/server/plugins/engine/components/CheckboxesField.ts, runner/src/server/plugins/engine/components/DatePartsField.ts, runner/src/server/plugins/engine/components/DateTimePartsField.ts, runner/src/server/plugins/engine/components/FileUploadField.ts, runner/src/server/plugins/engine/components/ListFormComponent.ts, runner/src/server/plugins/engine/components/MonthYearField.ts, runner/src/server/plugins/engine/components/MultilineTextField.ts, runner/src/server/plugins/engine/components/NumberField.ts, runner/src/server/plugins/engine/components/TelephoneNumberField.ts, runner/src/server/plugins/engine/components/TextField.ts, runner/src/server/plugins/engine/components/TimeField.ts, runner/src/server/plugins/engine/components/YesNoField.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/test/cases/server/plugins/engine/datepartsfield.test.ts
Previously the `customValidationMessage` property was being used on a couple of fields, however this validation message would override any other messages, meaning you couldn't have different messages for different validation scenarios.
We have now added a new option, `customValidationMessages`, which can be added to most field types. This option takes the same arguments as `(joi.messages)[https://joi.dev/api/?v=17.12.2#anymessagesmessages]`, allowing you to override specific validation errors as opposed to all of them.
=> fix: allow more dynamic error messaging

designer/client/i18n/translations/en.translation.json, designer/client/outputs/__tests__/output-edit.jest.tsx, designer/client/outputs/notify-edit.tsx, designer/client/outputs/output-edit.tsx, designer/client/outputs/types.ts, model/src/data-model/types.ts, model/src/schema/schema.ts, runner/src/server/plugins/engine/models/submission/NotifyModel.ts, runner/src/server/services/notifyService.ts, runner/src/server/services/statusService.ts
Previously there was no input validation on text fields relating to markdown formatting. This meant that users could enter markdown formatted text into text fields and this would be rendered properly by GOV.UK Notify. This could lead to vulnerabilities relating to phishing / social engineering attacks.
A flag has now been added to the notify output configuration to escape these URLs. This is currently optional and will be disabled by default, however it is **strongly recommended** this is turned on for all notify outputs that do not explicitly require users to complete answers with markdown formatting.
=> fix: added option to escape markdown links in notify personalisation

model/src/schema/schema.ts
Previously only fully qualified domain names were allowed to be specified for redirects, due to a .uri() validator on the page schema. This has now been removed
=> fix: Allow form paths in redirects

e2e/cypress/e2e/runner/dateValidation.feature, e2e/cypress/e2e/runner/dateValidation.js, e2e/cypress/fixtures/date-validation.json, e2e/cypress/fixtures/date.json, e2e/cypress/support/step_definitions/runner/i_navigate_to_string.js, e2e/cypress/support/step_definitions/runner/i_navigate_to_the_string_form.js, e2e/cypress/support/step_definitions/runner/the_form_string_exists.js, runner/src/server/plugins/engine/components/DatePartsField.ts
Date schema was not being properly set for maxDaysInFuture/maxDaysInPast
- set date schema so dates can be validated 
=> fix: date validation for maxDaysInPast and maxDaysInFuture 

runner/config/test.json, runner/src/server/services/statusService.ts, runner/test/cases/server/services/statusService.getViewModel.test.ts, runner/test/cases/server/status.test.json
When using render-able strings in the confirmationPage definition, e.g. 
```json5
"specialPages": {
"confirmationPage": {
"customText": {
"nextSteps": "Your application has been sent to the {{ appointmentLocation.post }}"      
}
}
},
```
where `appointmentLocation.post` would be a value like "British Embassy in Helsinki",
the string would first be rendered as "Your application has been sent to the British Embassy in Helsinki".
However, it would change the in-memory form definition, to be 
```json5
"specialPages": {
"confirmationPage": {
"customText": {
"nextSteps": "Your application has been sent to the British Embassy in Helsinki"      
}
}
},
```
now that there is no nunjucks templating - this string would no longer change depending on any users' answers. All users would see "Your …
=> fix: fix confirmation page definition overwrites 

runner/config/custom-environment-variables.json, runner/config/default.js, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/services/upload/uploadService.ts, runner/src/server/utils/configSchema.ts
- add `maxClientFileSize` / `"MAX_CLIENT_FILE_SIZE"` - the runner will reject requests larger than this size (b)
- add `maxFileSizeStringInMb` / `"MAX_FILE_SIZE_STRING_IN_MB"` - which is what is *rendered* in errors. This error could originate from the runner _or_ the document upload API  
=> fix: allow maxClientFileSize and maxApiFileSizeMb to be configurable

runner/src/server/views/confirmation.html
Sometimes it might be necessary to render html, such as links, in payment skipped and next steps text. To solve this, a change has been made to the confirmation template so that html should now be rendered properly.
=> feature: allow html to be rendered in next steps and payment skipped text

e2e/cypress/fixtures/html-templating-example.json, model/src/components/types.ts, model/src/data-model/types.ts, runner/src/server/forms/html-templating-example.json, runner/src/server/plugins/engine/components/ContextComponent.ts, runner/src/server/plugins/engine/components/ContextComponentCollection.ts, runner/src/server/plugins/engine/components/index.ts, runner/src/server/plugins/engine/models/FormModel.ts, runner/src/server/views/confirmation.html
Previously fields that had been exposed to context would become available throughout the form, however would only be available by their component name, and not by the `${section}.${name}` path. This would cause issues if there were two exposed components with the same name.
This has been fixed by creating a new `ContextComponentCollection` and `ContextComponent` which can pass the section name to the exposed components, therefore allowing them to be grouped by their section name.
=> fix: group exposed components by section to expose to context

e2e/cypress/e2e/runner/initialiseSession.js, e2e/cypress/fixtures/initialiseSession.json, model/src/data-model/types.ts, runner/src/server/plugins/engine/models/FormModel.ts, runner/src/server/plugins/engine/models/SummaryViewModel.ts, runner/src/server/plugins/engine/models/submission/EmailModel.ts, runner/src/server/plugins/engine/models/submission/NotifyModel.ts, runner/src/server/plugins/engine/models/submission/Outputs.ts, runner/src/server/plugins/engine/models/submission/WebhookModel.ts, runner/src/server/plugins/engine/models/submission/__tests__/WebhookModel.test.json, runner/src/server/plugins/engine/models/submission/__tests__/WebhookModel.test.ts, runner/src/server/plugins/engine/models/submission/index.ts, runner/src/server/plugins/engine/models/submission/types.ts, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts, runner/src/server/schemas/types.ts, runner/test/cases/server/plugins/engine/SummaryPageController.test.ts, runner/test/cases/server/plugins/engine/WebhookModel.test.ts
This is a refactor of SummaryViewModel and the outputs it creates.
Previously, SummaryViewModel was created to reduce the size of SummaryPageController and make the code more readable. Much of SummaryPageController's constructor code was just moved to SummaryViewModel, including code which created `outputs`. 
It was easiest to generate outputs (specifically the webhook output) from the SummaryViewModel, since it was a "flattened" form of the state data, which included the "human readable" titles of fields. However, some additional iteration/nested loops still happened between SummaryViewModel.details (i.e. what is needed to render the summary page) and pages to "fill in the gaps". 
This has caused tight coupling between SummaryViewModel.details and WebhookModel. The tight coupling makes …
=> minor: SummaryViewModel outputs

.github/workflows/lint-and-test.yml, e2e/cypress/fixtures/html-templating-example.json, runner/src/server/plugins/engine/components/ContextComponent.ts, runner/src/server/plugins/engine/components/ContextComponentCollection.ts
Previously when fields were exposed to context, if two fields were in the same section, the second field would overwrite the value of the first field. This is due to the way the value object is built for fields in sections, and how `Object.assign` works.
The `ContextComponentCollection.getFormDataFromState` function has now been changed so that the context state does not get overwritten anymore.
=> Bug: multiple exposed fields in a section causes context to be overwritten

docs/runner/submission-queue.md, runner/config/custom-environment-variables.json, runner/src/server/services/pgBossQueueService.ts, runner/src/server/utils/configSchema.ts
This is part of pgboss v9 to v10 migration. 
- Allow `QUEUE_DATABASE_SCHEMA_NAME` to be configured
=> feature: allow schema name to be configured

README.md, docs/runner/submission-queue.md, runner/package.json, runner/src/server/services/pgBossQueueService.ts, yarn.lock
=> feat: upgrade pgboss to v10

designer/client/conditions/SelectConditions.tsx
- Trim the leading `.` so conditions render in the select a condition dropdown 
=> fix: trim leading `.` so conditions render

runner/src/server/plugins/engine/components/CheckboxesField.ts
Fix for bug raised in this ticket https://jira.collab.test-and-trace.nhs.uk/browse/CAR-190 
When CheckboxesField was on same page as several other Radio components and user tries to proceed with 2 checkbox answers ticket but not the Radio components, then a 500 error presented. 
=> fix: Checkboxes Field bug

.github/workflows/deploy-development.yml
Deployments triggered on merge to main are currently failing due to heroku cli not being available. 
- Log into heroku using npx
=> fix: log into heroku via npx

designer/package.json, model/package.json, package.json, runner/package.json, runner/src/client/sass/_govuk.scss, runner/src/client/sass/_upload-dialog.scss, runner/src/client/sass/application.scss, runner/src/server/plugins/views.ts, runner/src/server/routes/public.ts, runner/src/server/views/layout.html, yarn.lock
- Update govuk-frontend to 4.10.0 for GDS rebrand
- Add rebrand background colour 
<details><summary>Screenshot without updated background colour (see below footer)</summary>
<p><img width="1466" alt="Screenshot 2025-06-10 at 13 45 22" src="https://github.com/user-attachments/assets/8dca06ac-e399-42ad-8dae-5fb254840431" />
</p>
</details> 
<details><summary>Screenshot with updated background colour (see below footer)</summary>
<p><img width="1466" alt="Screenshot 2025-06-10 at 13 45 44" src="https://github.com/user-attachments/assets/8112841a-a6d5-45d4-99be-ebf4fce2fe76" />
</p>
</details> 
- Update asset routes for favicons
the testing if …
=> feature: update govuk-frontend to v4.10.0 for rebrand

runner/src/client/sass/application.scss, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/pageControllers/RepeatingSectionSummaryPageController.ts, runner/src/server/plugins/engine/pageControllers/helpers.ts, runner/src/server/plugins/engine/pageControllers/index.ts, runner/src/server/views/partials/summary-card.html, runner/src/server/views/partials/summary-row.html, runner/src/server/views/repeating-section-summary.html, runner/src/server/views/summary.html
- New page controller, which displays a summary of sections whose title matches the page title followed by a number. (E.g. if the page has the title 'Close contact', sections with titles 'Close contact 1', 'Close contact 2' etc. would display). It also gives you the option to remove sections.
- Details are displayed as summary cards in the associated view file. I've also developed the ability to display sections as cards in the summary page.
New feature (non-breaking change which adds functionality)
=> RepeatingSectionSummaryPageController and summary cards

.github/workflows/branch--lint-unit-and-smoke-test.yml, .github/workflows/dependency-review.yml, .github/workflows/smoke-test.yml, docker-compose.smoke.yml
#1336 is blocked by CI failing to run the smoke test workflow. https://github.com/XGovFormBuilder/digital-form-builder/actions/runs/16147889277/job/45571894905?pr=1336#step:10:5625
How GitHub actions deal with missing images/repos seems to have changed. I also got the same error when opening a PR to verify it is not an issue with git repository permissions.
**changes made**
- update smoke-test.yml to build the required containers (runner and designer)
- add `build` parameter to smoke-test.yml, so build behaviour can be toggled. 
- We can consider setting to false if we're running this on the main branch for example. On main we can just pull the published latest images
- update docker-compose.smoke.yml to pull from our ghcr 
- remove unused runner-cache-ref and designer-cache-ref since …
=> chore: fix smoke test pull image error

e2e/cypress/e2e/runner/MiniSummaryPageController.feature, runner/src/server/plugins/engine/pageControllers/MiniSummaryPageController.ts
Mini summary change links weren't working correctly
Change links did not successfully redirect to the mini summary page after an edit has been made
- Changed approach for altering the change link URL
- E2E test updated to include change link functionality
What is the type of change you are making?
PR titles should be prefixed with the type of change you are making, based on the [README.md#versioning](https://github.com/XGovFormBuilder/digital-form-builder?tab=readme-ov-file#versioning).
This is so that when performing a squash merge, the PR title is automatically used as the commit message.
Have you updated the PR title to match the type of change you are making?
Have you added automated tests?
Have you manually tested your changes?
Have you attached an example form JSON or snippet for …
=> fix: MiniSummaryPageController change link issue

.github/workflows/beta--lint-unit-build-and-publish-images.yml, .github/workflows/main--lint-unit-build-and-publish-images.yml
Remove use of GHCR_PAT which is a personal access token (used before GITHUB_TOKEN was added to GitHub actions by default). Workflows should not be tied to a single user
Not required - GITHUB_TOKEN is used in GitHub actions already
=> chore(ci): use GITHUB_TOKEN instead of GHCR_PAT
